import ThemeRegistry from '@/providers/ThemeRegistry';
import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react';
import { Footer } from '@/components/Footer/Footer';
import { AppBar, Button, Container, Toolbar, Typography } from '@mui/material';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const HEADER_SX = {
  flexGrow: 1,
}

export default function RootLayout({
 children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
    <body>
      <ThemeRegistry options={{ key: 'mui' }}>
        <div className="layout">
          <AppBar position="static">
            <Toolbar>
              <Typography variant="h6" component="div" sx={HEADER_SX}>
                React-Router + Material-UI
              </Typography>
              <Button component={Link} href="/" color="inherit">
                Photos
              </Button>
              <Button component={Link} href="/posts" color="inherit">
                Posts
              </Button>
              <Button component={Link} href="/comments" color="inherit">
                Comments
              </Button>
              <Button component={Link} href="/users" color="inherit">
                Users
              </Button>
            </Toolbar>
          </AppBar>
          <main className="main">
            <Container>
              {children}
            </Container>
          </main>
          <Footer />
        </div>
      </ThemeRegistry>
    </body>
    </html>
  )
}
